<a href="https://colab.research.google.com/github/nou619/learning-PyTorch/blob/main/leaningpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [1]:
print('yo')

yo


In [2]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX=torch.tensor([ [7,8], [9,10] ])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.ndim

2

In [12]:
TENSOR=torch.tensor([[[1,2,3], [4,5,6] ,[7,8,9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5141, 0.0391, 0.6268, 0.3421],
        [0.7199, 0.9415, 0.7863, 0.2545],
        [0.2965, 0.3883, 0.6845, 0.0290]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor=torch.rand(size=(3,224,224))

In [18]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [19]:
zeros=torch.zeros(3,4)

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(3,1)

In [22]:
ones

tensor([[1.],
        [1.],
        [1.]])

In [23]:
TENSOR.dtype

torch.int64

In [24]:
zeros.dtype

torch.float32

In [25]:
torch.range(1,5)

/tmp/ipython-input-2886557097.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [26]:
zero_to_four=torch.arange(5)
zero_to_four

tensor([0, 1, 2, 3, 4])

In [27]:
five_zeros=torch.zeros_like(input=zero_to_four)
five_zeros

tensor([0, 0, 0, 0, 0])

In [28]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None, requires_grad=False)

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
#getting information from tensors
#1.tensors not right datatype-
#2.tensors not right shape
#3.tensors not on the right device

In [34]:
some_tensor=torch.rand(3,4)

In [35]:
print(f"datatype of tensor  {some_tensor.dtype}")

datatype of tensor  torch.float32


In [36]:
print(f"device of tensor  {some_tensor.device}")

device of tensor  cpu


tensor operations


In [37]:
tensor=torch.tensor([1,2,3])

In [38]:
tensor+10


tensor([11, 12, 13])

In [39]:
tensor*10

tensor([10, 20, 30])

In [40]:
tensor-10

tensor([-9, -8, -7])

In [41]:
tensor//10

tensor([0, 0, 0])

In [42]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
#torch.add

In [46]:
###matrix multiplication

In [47]:
torch.matmul(tensor,tensor)

tensor(14)

In [48]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value


CPU times: user 644 µs, sys: 0 ns, total: 644 µs
Wall time: 2.7 ms


tensor(14)

In [49]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 589 µs, sys: 0 ns, total: 589 µs
Wall time: 1.51 ms


tensor(14)

In [50]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3400, 0.5100, 0.7183],
        [0.0166, 0.0314, 0.0823],
        [0.5012, 0.7304, 0.9024]])

In [51]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.0404, 0.0984, 0.0744],
        [0.1436, 0.3287, 0.2636],
        [0.1517, 0.3230, 0.2780]])

In [52]:
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,2)

In [53]:
tensor_b

tensor([[0.5086, 0.0221],
        [0.3107, 0.9471],
        [0.4557, 0.4671]])

In [54]:
tensor_b.T

tensor([[0.5086, 0.3107, 0.4557],
        [0.0221, 0.9471, 0.4671]])

In [55]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
#add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [57]:
x_reshaped=x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [58]:
#change the view

In [59]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x_stacked=torch.stack([x,x,x,x],dim=1)

In [63]:
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [64]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [65]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [66]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [67]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [68]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [69]:
import torch
x = torch.tensor([[[5, 6, 7]]])
print(x.shape)


torch.Size([1, 1, 3])


In [70]:
y = torch.squeeze(x)
print(y.shape)


torch.Size([3])


In [71]:
y.unsqueeze(dim=0)

tensor([[5, 6, 7]])

In [72]:
y=y.unsqueeze(dim=0)
y

tensor([[5, 6, 7]])

In [73]:
#torch.permute

In [74]:
x=torch.randn(2,3,5)
x

tensor([[[-0.5175, -0.1071,  1.1028,  0.3042, -0.4896],
         [-0.7535,  0.4111, -0.5679,  0.4139, -0.4945],
         [-0.3879,  0.7993, -0.6095, -0.7342,  1.6276]],

        [[ 0.0911,  0.0227, -1.1604,  0.0795, -0.6697],
         [-0.6538, -0.8946,  0.9749, -0.3689, -1.0021],
         [ 0.7682,  1.1137,  1.9998,  0.8881, -1.3734]]])

In [75]:
x.size()

torch.Size([2, 3, 5])

In [76]:
x2=torch.permute(x,(2,0,1))

In [77]:
x2.size()
x[0,0,0]

tensor(-0.5175)

In [78]:
#understanding permute:
x2[0,0,0]=0.196
x[0,0,0]

tensor(0.1960)

In [79]:
x[:,0]

tensor([[ 0.1960, -0.1071,  1.1028,  0.3042, -0.4896],
        [ 0.0911,  0.0227, -1.1604,  0.0795, -0.6697]])

In [80]:
x[0]

tensor([[ 0.1960, -0.1071,  1.1028,  0.3042, -0.4896],
        [-0.7535,  0.4111, -0.5679,  0.4139, -0.4945],
        [-0.3879,  0.7993, -0.6095, -0.7342,  1.6276]])

In [81]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [82]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [83]:
x[:,0]

tensor([[1, 2, 3]])

In [84]:
x[0][0]

tensor([1, 2, 3])

In [85]:
x[0][0][1]

tensor(2)

In [86]:
x[0][1][1]

tensor(5)

In [87]:
x[:,:,0]

tensor([[1, 4, 7]])

In [88]:
#numpy

In [89]:
#numpy array tensor
array=np.arange(1.0,8.0)

tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
array+=1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [91]:
tensor=torch.ones(7)
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [92]:
numpy_tensor=tensor.numpy()# changes both the tensor and numpy tensor
tensor,numpy_tensor,array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [93]:
tensor= tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
torch.rand(3,3)

tensor([[0.8152, 0.9261, 0.4089],
        [0.0700, 0.8476, 0.6569],
        [0.1127, 0.9270, 0.6431]])

In [95]:
randA=torch.rand(3,4)
randB=torch.rand(3,4)
print(randA==randB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [96]:
random_seed=42
torch.manual_seed(random_seed)
randC=torch.rand(3,4)
torch.manual_seed(random_seed)
randD=torch.rand(3,4)
randC,randD
print(randC==randD)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [97]:
randC,randD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

running tensors and pytorch objects on the gpu
(gpu=faster compulation on numbers)

In [98]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [99]:
torch.cuda.is_available()

False

In [100]:
!lspci | grep -i nvidia


/bin/bash: line 1: lspci: command not found


In [101]:
import torch

if torch.cuda.is_available():
    print("🔥 GPU detected:", torch.cuda.get_device_name(0))
else:
    print("💀 No GPU available.")


💀 No GPU available.


In [102]:
torch.cuda.device_count()

0

In [104]:
x.device

device(type='cpu')

move tensor to gpu if available

In [110]:
x_gpu=x.to(device)
x_gpu.device

device(type='cpu')