<a href="https://colab.research.google.com/github/nou619/learning-PyTorch/blob/main/leaningpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
print('yo')

yo


In [106]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt


In [107]:
print(torch.__version__)

2.8.0+cu126


In [108]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [109]:
scalar.ndim

0

In [110]:
scalar.item()

7

In [111]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [112]:
vector.shape

torch.Size([2])

In [113]:
MATRIX=torch.tensor([ [7,8], [9,10] ])

In [114]:
MATRIX.shape

torch.Size([2, 2])

In [115]:
MATRIX.ndim

2

In [116]:
TENSOR=torch.tensor([[[1,2,3], [4,5,6] ,[7,8,9]]])

In [117]:
TENSOR.ndim

3

In [118]:
TENSOR.shape

torch.Size([1, 3, 3])

In [119]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [120]:
random_tensor.ndim

2

In [121]:
random_image_size_tensor=torch.rand(size=(3,224,224))

In [122]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [123]:
zeros=torch.zeros(3,4)

In [124]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [125]:
ones=torch.ones(3,1)

In [126]:
ones

tensor([[1.],
        [1.],
        [1.]])

In [127]:
TENSOR.dtype

torch.int64

In [128]:
zeros.dtype

torch.float32

In [129]:
torch.range(1,5)

/tmp/ipython-input-2886557097.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [130]:
zero_to_four=torch.arange(5)
zero_to_four

tensor([0, 1, 2, 3, 4])

In [131]:
five_zeros=torch.zeros_like(input=zero_to_four)
five_zeros

tensor([0, 0, 0, 0, 0])

In [132]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None, requires_grad=False)

In [133]:
float_32_tensor.dtype

torch.float32

In [134]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [135]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [136]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [137]:
#getting information from tensors
#1.tensors not right datatype-
#2.tensors not right shape
#3.tensors not on the right device

In [138]:
some_tensor=torch.rand(3,4)

In [139]:
print(f"datatype of tensor  {some_tensor.dtype}")

datatype of tensor  torch.float32


In [140]:
print(f"device of tensor  {some_tensor.device}")

device of tensor  cpu


tensor operations


In [141]:
tensor=torch.tensor([1,2,3])

In [142]:
tensor+10


tensor([11, 12, 13])

In [143]:
tensor*10

tensor([10, 20, 30])

In [144]:
tensor-10

tensor([-9, -8, -7])

In [145]:
tensor//10

tensor([0, 0, 0])

In [146]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [147]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [148]:
tensor

tensor([1, 2, 3])

In [149]:
#torch.add

In [150]:
###matrix multiplication

In [151]:
torch.matmul(tensor,tensor)

tensor(14)

In [152]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value


CPU times: user 211 µs, sys: 20 µs, total: 231 µs
Wall time: 235 µs


tensor(14)

In [153]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 481 µs, sys: 0 ns, total: 481 µs
Wall time: 643 µs


tensor(14)

In [154]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2055, 0.5883, 1.0170],
        [0.5719, 1.3500, 1.2323],
        [0.4267, 0.9260, 0.4668]])

In [155]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[1.0480, 0.7547, 0.6157],
        [0.7930, 0.4609, 0.3876],
        [0.7976, 0.3543, 0.3121]])

In [156]:
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,2)

In [157]:
tensor_b

tensor([[0.5268, 0.6694],
        [0.3213, 0.4008],
        [0.2892, 0.9977]])

In [158]:
tensor_b.T

tensor([[0.5268, 0.3213, 0.2892],
        [0.6694, 0.4008, 0.9977]])

In [159]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [160]:
#add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [161]:
x_reshaped=x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [162]:
#change the view

In [163]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [164]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [165]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [166]:
x_stacked=torch.stack([x,x,x,x],dim=1)

In [167]:
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [168]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [169]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [170]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [171]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [172]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [173]:
import torch
x = torch.tensor([[[5, 6, 7]]])
print(x.shape)


torch.Size([1, 1, 3])


In [174]:
y = torch.squeeze(x)
print(y.shape)


torch.Size([3])


In [175]:
y.unsqueeze(dim=0)

tensor([[5, 6, 7]])

In [176]:
y=y.unsqueeze(dim=0)
y

tensor([[5, 6, 7]])

In [177]:
#torch.permute

In [178]:
x=torch.randn(2,3,5)
x

tensor([[[-1.1620, -1.2845,  0.8447,  1.0704, -0.9793],
         [ 0.5855,  0.4987, -0.7475, -0.9146, -0.1143],
         [ 2.1611,  0.3076, -0.2680, -0.1583, -1.7651]],

        [[ 0.1357,  1.7733, -0.0494, -1.0806,  0.5515],
         [ 1.3083, -0.0726, -0.0742, -0.7433, -0.4912],
         [ 0.4961, -1.9448, -2.1279,  1.6423,  1.2017]]])

In [179]:
x.size()

torch.Size([2, 3, 5])

In [180]:
x2=torch.permute(x,(2,0,1))

In [181]:
x2.size()
x[0,0,0]

tensor(-1.1620)

In [182]:
#understanding permute:
x2[0,0,0]=0.196
x[0,0,0]

tensor(0.1960)

In [183]:
x[:,0]

tensor([[ 0.1960, -1.2845,  0.8447,  1.0704, -0.9793],
        [ 0.1357,  1.7733, -0.0494, -1.0806,  0.5515]])

In [184]:
x[0]

tensor([[ 0.1960, -1.2845,  0.8447,  1.0704, -0.9793],
        [ 0.5855,  0.4987, -0.7475, -0.9146, -0.1143],
        [ 2.1611,  0.3076, -0.2680, -0.1583, -1.7651]])

In [185]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [186]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [187]:
x[:,0]

tensor([[1, 2, 3]])

In [188]:
x[0][0]

tensor([1, 2, 3])

In [189]:
x[0][0][1]

tensor(2)

In [190]:
x[0][1][1]

tensor(5)

In [191]:
x[:,:,0]

tensor([[1, 4, 7]])

In [192]:
#numpy

In [193]:
#numpy array tensor
array=np.arange(1.0,8.0)

tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [194]:
array+=1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [195]:
tensor=torch.ones(7)
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [196]:
numpy_tensor=tensor.numpy()# changes both the tensor and numpy tensor
tensor,numpy_tensor,array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [197]:
tensor= tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [198]:
torch.rand(3,3)

tensor([[0.3507, 0.6683, 0.4601],
        [0.9545, 0.1936, 0.8199],
        [0.3752, 0.6261, 0.6456]])

In [199]:
randA=torch.rand(3,4)
randB=torch.rand(3,4)
print(randA==randB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [200]:
random_seed=42
torch.manual_seed(random_seed)
randC=torch.rand(3,4)
torch.manual_seed(random_seed)
randD=torch.rand(3,4)
randC,randD
print(randC==randD)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [201]:
randC,randD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

running tensors and pytorch objects on the gpu
(gpu=faster compulation on numbers)

In [202]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [203]:
torch.cuda.is_available()

False

In [205]:
!lspci | grep -i nvidia


/bin/bash: line 1: lspci: command not found


In [206]:
import torch

if torch.cuda.is_available():
    print("🔥 GPU detected:", torch.cuda.get_device_name(0))
else:
    print("💀 No GPU available.")


💀 No GPU available.
