<a href="https://colab.research.google.com/github/nou619/learning-PyTorch/blob/main/leaningpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('yo')

yo


In [2]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX=torch.tensor([ [7,8], [9,10] ])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.ndim

2

In [12]:
TENSOR=torch.tensor([[[1,2,3], [4,5,6] ,[7,8,9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0985, 0.3075, 0.2199, 0.7209],
        [0.0277, 0.9677, 0.2861, 0.6157],
        [0.8983, 0.3356, 0.6875, 0.3834]])

In [16]:
random_tensor.ndim

2

In [17]:
random_image_size_tensor=torch.rand(size=(3,224,224))

In [18]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [19]:
zeros=torch.zeros(3,4)

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(3,1)

In [22]:
ones

tensor([[1.],
        [1.],
        [1.]])

In [23]:
TENSOR.dtype

torch.int64

In [24]:
zeros.dtype

torch.float32

In [25]:
torch.range(1,5)

/tmp/ipython-input-2886557097.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [26]:
zero_to_four=torch.arange(5)
zero_to_four

tensor([0, 1, 2, 3, 4])

In [27]:
five_zeros=torch.zeros_like(input=zero_to_four)
five_zeros

tensor([0, 0, 0, 0, 0])

In [28]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None, requires_grad=False)

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
#getting information from tensors
#1.tensors not right datatype-
#2.tensors not right shape
#3.tensors not on the right device

In [34]:
some_tensor=torch.rand(3,4)

In [35]:
print(f"datatype of tensor  {some_tensor.dtype}")

datatype of tensor  torch.float32


In [36]:
print(f"device of tensor  {some_tensor.device}")

device of tensor  cpu


tensor operations


In [37]:
tensor=torch.tensor([1,2,3])

In [38]:
tensor+10


tensor([11, 12, 13])

In [39]:
tensor*10

tensor([10, 20, 30])

In [40]:
tensor-10

tensor([-9, -8, -7])

In [41]:
tensor//10

tensor([0, 0, 0])

In [42]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
#torch.add

In [46]:
###matrix multiplication

In [47]:
torch.matmul(tensor,tensor)

tensor(14)

In [48]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value


CPU times: user 300 µs, sys: 1.06 ms, total: 1.36 ms
Wall time: 1.31 ms


tensor(14)

In [49]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 326 µs, total: 326 µs
Wall time: 259 µs


tensor(14)

In [50]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5986, 0.8941, 0.5121],
        [0.3380, 0.4563, 0.2892],
        [0.6093, 1.0063, 0.5211]])

In [51]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.8246, 0.0554, 0.5363],
        [0.8943, 0.0886, 1.0539],
        [0.9800, 0.0813, 0.8941]])

In [52]:
tensor_a=torch.rand(3,4)
tensor_b=torch.rand(3,2)

In [53]:
tensor_b

tensor([[0.7854, 0.5204],
        [0.1308, 0.9496],
        [0.2699, 0.9878]])

In [54]:
tensor_b.T

tensor([[0.7854, 0.1308, 0.2699],
        [0.5204, 0.9496, 0.9878]])

In [55]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
#add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [57]:
x_reshaped=x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [58]:
#change the view

In [59]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x_stacked=torch.stack([x,x,x,x],dim=1)

In [63]:
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [64]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [65]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [68]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [67]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [69]:
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [70]:
import torch
x = torch.tensor([[[5, 6, 7]]])
print(x.shape)


torch.Size([1, 1, 3])


In [71]:
y = torch.squeeze(x)
print(y.shape)


torch.Size([3])


In [75]:
y.unsqueeze(dim=0)

tensor([[5, 6, 7]])

In [79]:
y=y.unsqueeze(dim=0)
y

tensor([[[[5, 6, 7]]]])

In [ ]:
#torch.permute

In [86]:
x=torch.randn(2,3,5)
x

tensor([[[-2.1070, -0.7391,  0.5636,  0.6640, -0.4787],
         [ 0.8583, -0.6333, -0.1359, -1.3581,  0.1097],
         [-1.0509,  0.1226, -0.4190,  0.3229, -0.0187]],

        [[-1.1199, -1.3375,  0.8174, -0.5698,  1.0430],
         [ 0.5858, -0.1957, -0.0076,  0.5137, -0.1696],
         [-0.3222, -0.9731, -2.0496, -1.0193, -0.6580]]])

In [87]:
x.size()

torch.Size([2, 3, 5])

In [94]:
x2=torch.permute(x,(2,0,1))

In [97]:
x2.size()
x[0,0,0]

tensor(-2.1070)

In [98]:
#understanding permute:
x2[0,0,0]=0.196
x[0,0,0]

tensor(0.1960)